# Generated by Django 5.1.4 on 2024-12-11 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='idRealEstateFinishing',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='idTransactionType',
        ),
        migrations.RemoveField(
            model_name='chalet',
            name='idRealEstateFinishing',
        ),
        migrations.RemoveField(
            model_name='chalet',
            name='idTransactionType',
        ),
        migrations.RemoveField(
            model_name='emptyland',
            name='idRealEstateFinishing',
        ),
        migrations.RemoveField(
            model_name='emptyland',
            name='idTransactionType',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='idRealEstateFinishing',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='idTransactionType',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='idRealEstateFinishing',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='idTransactionType',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='idRealEstateFinishing',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='idTransactionType',
        ),
    ]
